site_name: GreenDevOps Framework
site_description: Official documentation for the GreenDevOps plugin and AI build optimizer.
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Quick Start Guides:
      - Docker Deployment: quick_start_docker.md
      - Local Deployment: quick_start_local.md
